using System.Security;
using Xunit;
using Moq;
using SampleProject;

namespace Tests
{
    public class Test_StaticClass
    {
        private StaticClass staticclass;
        public Test_StaticClass()
        {
        }

        [Fact]
        public void Test_StaticMethod()
        {
            Assert.Fail("autogenerated");
        }
    }
}