using System.Security;
using Xunit;
using Moq;
using SampleProject;

namespace Tests
{
    public class Test_AnotherClass
    {
        private AnotherClass anotherclass;
        public Test_AnotherClass()
        {
        }

        [Fact]
        public void Test_anotherThing()
        {
            var actual = anotherclass.anotherThing();
            var expected = default(List<int>);
            Assert.Equal(expected, actual);
            Assert.Fail("autogenerated");
        }
    }
}