using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using Moq;
using SampleProject;

namespace Tests
{
    public class Test_AnotherCoolTest
    {
        private AnotherCoolTest anothercooltest;
        public Test_AnotherCoolTest()
        {
        }

        [Fact]
        public void Test_GetNumber()
        {
            var a = default(int);
            var actual = anothercooltest.GetNumber(a);
            var expected = default(int);
            Assert.Equal(expected, actual);
            Assert.Fail("autogenerated");
        }
    }
}